name: Automatic deploy of my vite react app

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '25'
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install and Build
        working-directory: ./
        run: |
          npm ci
          npm run build

      - name: Deploy to GitHub Pages
        if: github.event_name == 'push'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/
          keep_files: false